version: '3.8'

services:
  web:
    build: .
    command: gunicorn bookstore_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: bookstore_db
      POSTGRES_USER: bookstore_user
      POSTGRES_PASSWORD: bookstore_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
